[package]
name = "Kata4"
version = "0.1.0"
authors = ["lDiego257 <lDiego257>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
